### ISSUE TITLE
Transaction rewards

### ISSUE THREAD

**Issue by alexnu** [lastmjs/eth-total-supply#20]
Hi,

Please forgive my ignorance as I'm new to Ethereum. I was wondering shouldn't we include transaction fees in block reward calculation?

When looking at various [Statistics websites](https://bitinfocharts.com/ethereum/), I always see three numbers adding up to the total block reward:

static block reward + trx fees + uncle inclusion rewards + uncle rewards

![Screenshot 2021-05-03 at 2 26 09 PM](https://user-images.githubusercontent.com/3530783/116870639-89bea800-ac1b-11eb-8f0d-57348d1a40d6.png)

Why are transaction fees not included in total supply calculation?

**Comment by lastmjs** [comment]
The purpose of these calculations is to determine the supply of ETH, and
the only way for ETH to be created is through the block reward created by
the protocol.

Transaction fees do not create new ETH, they just redistribute it. Thus,
not relevant for determining the supply of ETH.

If you're interested in determining the total ETH reward given to miners
per block, then yes you would want to include transaction fees.

**Comment by alexnu** [comment]
Hi @lastmjs 

I understand now, thank you very much for the detailed explanation. Closing this.
