### ISSUE TITLE
Assertion is not Verification

### ISSUE THREAD

**Issue by JoelBondurant** [lastmjs/eth-total-supply#6]
May as well hard code a final result, rather than pretend to do a calculation based on a supposed supply from the yellow pages.

https://github.com/lastmjs/eth-total-supply/blob/10fa8a52dce617548553d9653a4b56062bf4ba38/calculate-block-reward-issuance.ts#L101

**Comment by androolloyd** [comment]
That would be 3 ether in big number motion? Or am I missing something?

**Comment by lastmjs** [comment]
@androolloyd the values are in WEI, which is 10^18 ETH.

@JoelBondurant The base block rewards are hard-coded into each client, there is no other way to determine issuance (determining supply by summing account balances is another method of determining supply).

That function has documented multiple locations where you can verify the numbers that each client is using to issue ETH. Here they are:
```javascript
/**
 * Returns the base block reward for a block based on block number.
 * The rewards started at 5 ETH per block, and have been changed twice with hard forks.
 * These rewards can be verified in the Ethereum client implementations.
 * Some of these resources are included below:
 * Geth block reward definitions: https://github.com/ethereum/go-ethereum/blob/master/consensus/ethash/consensus.go#L40
 * Geth hard fork block number definitions: https://github.com/ethereum/go-ethereum/blob/master/params/config.go#L55
 * Open Ethereum block reward and hard fork block number definitions: https://github.com/openethereum/openethereum/blob/master/ethcore/res/ethereum/foundation.json, look at engine.Ethash.params.blockReward
 * Nethermind block reward and hard fork block number definitions: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/foundation.json, look at engine.Ethash.params.blockReward
 */
```
I'm not sure how this could be improved, do you have any suggestions?

**Comment by tjayrush** [comment]
As far as I can tell, the Yellow Paper does not mention the fact that the `baseReward` changes depending on the fork. It's totally correct to say it does, and the code clearly works this way, but the Yellow Paper doesn't say that. See Equation 116. It would probably be beneficial to submit an issue report to the Yellow Paper. Unless I'm missing something. I'll submit it, if someone here can confirm my suspicion.

**Comment by tjayrush** [comment]
@JoelBondurant Totally agree that Assertion is not Verification. See https://github.com/Great-Hill-Corporation/trueblocks-core/blob/develop/src/other/issuance/README.md. This issue should be closed.

**Comment by JoelBondurant** [comment]
Closing, the scope of Ethereum is limited to assertions and not validations such as summing account balances.

**Comment by tjayrush** [comment]
Obviously, you've not been reading the work, as we show that we do actually verify the balances of every miner and every uncle miner at every block, and in every case it reconciles to the expected behavior as per the Yellow Paper. Happy to see this closed, though.

**Comment by JoelBondurant** [comment]
Plenty to follow here, empty values as expected per scope:
https://github.com/lastmjs/eth-total-supply#total-eth-account-balances-1

**Comment by lastmjs** [comment]
We've had our first values added: https://github.com/lastmjs/eth-total-supply#total-eth-supply
